<template id="pop-modal">
	<transition name="fade" @after-enter="content = true">
		<div
			v-if="container"
			class="modal-container"
			@click.self="content = false"
		>
			<transition name="burst" @after-leave="$emit('close')">
				<div v-if="content" class="modal">
					<h2 class="center">Export Playlist</h2>
					<div class="modal-form">
						<div class="input-row">
							<input
								id="playlist-name"
								v-model="name"
								type="text"
								name="Playlist Name"
							>
						</div>
						<div class="input-row">
							<textarea-autosize
								v-model="description"
								placeholder="Type something here..."
								:min-height="100"
							/>
						</div>
						<div class="input-row">
							<select v-model="is_private">
								<option value="true">Private Playlist</option>
								<option value="false">Public Playlist</option>
							</select>
							<button>Create Playlist</button>
						</div>
					</div>
				</div>
			</transition>
		</div>
	</transition>
</template>

<script>
export default {
	name: `PlaylistExportModal`,
	props: {
		config: {
			type: Object,
			required: true,
		}
	},
	data() {return {
		container: false,
		content: false,
		name: ``,
		is_private: true,
		description: `Playlist auto-generated by Top Lists for Spotify`,
	}},
	mounted() {
		let date = new Date();
		let month = date.getMonth() + 1;
		month = month < 10 ? `0${month}` : month;
		this.name = `Top ${this.config.limit || 10} - ${date.getFullYear()}/${month}/${date.getDate()}`;

		this.$nextTick(function() {
			this.container = true;
		});
	},
	methods: {},
}
</script>

<style scoped>
.modal-container {
	background-color: var(--modal-container-background);
	justify-content: center;
	align-items: center;
	position: fixed;
	display: flex;
	height: 100vh;
	width: 100vw;
	z-index: 10;
	left: 0;
	top: 0;
}

.modal {
	background-color: var(--modal-background);
	border-radius: var(--corner-rounding);
	color: var(--modal-text);
	text-align: center;
	overflow-y: auto;
	max-height: 85%;
	padding: 0 15px;
	z-index: 11;
	width: 90%;
}

div.modal-form {
	flex-direction: column;
	align-items: center;
	display: flex;
}

.input-row {
	justify-content: space-evenly;
	margin-bottom: 10px;
	flex-wrap: wrap;
	display: flex;
	width: 100%;
}

button {
	margin: 10px;
}

@media only screen and (min-width: 768px) {
	.modal {
		width: 50%;
		max-height: 75%;
	}
}
</style>